### ISSUE TITLE
Don't merge your own PR

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/Techspardha-18-prime#13]
I have been seeing you'll create a PR and merge it yourself.
Let someone review it, and he/she can merge it.

**Comment by phoenixking25** [comment]
we are using different branches to maintain the master branch working

**Comment by AnshulMalik** [comment]
Doesn't matter @phoenixking25 , then what's the point of creating a PR? you can just directly push to master.

**Comment by phoenixking25** [comment]
Arre @AnshulMalik aaj khatam karna hai kaam
please direct push in master enable kar do.
